#
# http://travis-ci.org configuration file for openMVG
#

language: cpp

compiler:
  - gcc
  #- clang: #Consider clang later, since cereal does not build fine on the clang CI version
  #  - "3.3"

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8

env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
    - BUILD_TYPE="Release"
    - BUILD_SYSTEM=`uname -s`
    - BUILD_PROCESSOR=`uname -p`
    - CXX="g++-4.8"

before_install:
 - gem install coveralls-lcov

before_script:
  - cd ..
  - mkdir build
  - cd build
  # Classic release build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON -DOpenMVG_USE_BOOST=ON . ../openMVG/src
  # Build for code coverage evaluation
  #- cmake -DOpenMVG_BUILD_COVERAGE=ON -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . ../openMVG/src

script:
# limit GCC builds to a reduced number of thread for the virtual machine
  - make -j 2
# Perform unit tests only on GCC builds
  - if [ "$CC" = "gcc" ]; then make test; fi
 
after_success:
  - mkdir gt_test
  - git clone --branch dev https://github.com/caymard/SfM_quality_evaluation.git gt_test/
  - cd gt_test
  - python EvaluationLauncher.py -s "../$BUILD_SYSTEM-$BUILD_PROCESSOR-$BUILD_TYPE" -i Benchmarking_Camera_Calibration_2008/ -o output -r results.json > gt_log.log 2>&1
  - cat gt_log.log | tail
  - cat results.json
  #- cd ../openMVG
  # If GCC: compute code coverage and export it to coveralls
  #- if [ "$CC" = "gcc" ];
  #  then
  #    lcov --directory ../build/openMVG --base-directory=./src --capture --output-file=coverage.info;
  #    lcov --remove coverage.info '/usr*' -o coverage.info;
  #    lcov --remove coverage.info '*_test.cpp*' -o coverage.info;
  #    lcov --remove coverage.info '*/third_party/*' -o coverage.info;
  #    lcov --remove coverage.info '*/src/dependencies/*' -o coverage.info;
  #    coveralls-lcov coverage.info;
  #  fi
