version: '1.0.{build}'

image: Visual Studio 2015

platform:
  - x64

configuration:
  - Release
  # - Debug

init:
# init runs before cache setup
# Force "release" or "debug" build in vcpkg at cmake level:  VCPKG_BUILD_TYPE=release
  - echo.set(VCPKG_BUILD_TYPE %CONFIGURATION%)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake

install:
    - git submodule update --init --recursive
#    - cmd: >-
#          call cudaInstallAppveyor.cmd
    - vcpkg upgrade
    - vcpkg list
    - vcpkg install
          boost-accumulators boost-atomic boost-container boost-date-time boost-exception boost-filesystem boost-graph boost-log boost-program-options boost-regex boost-serialization boost-system boost-thread
          openexr
          openimageio
          alembic
          geogram
          eigen3
          ceres
          --triplet %PLATFORM%-windows
    - vcpkg list


before_build:
    - md build
    - cd build
    - cmake .. -G "Visual Studio 14 2015 Win64"
            -DCMAKE_BUILD_TYPE=%CONFIGURATION%
            -DALICEVISION_USE_INTERNAL_CERES:BOOL=OFF
            -DALICEVISION_USE_CUDA:BOOL=OFF
            -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    - ls -l

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\aliceVision.sln
  parallel: true

# comment the above and uncomment the following to just build the dependencies
#build_script:
#  - echo "Dependencies installed."

cache:
  c:\tools\vcpkg\installed\
